=== asmbs/wp-schedule-builder/resources/schema/field_group.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://advancedcustomfields.com/json-schema/field_group",
    "type": "object",
    "definitions": {
        "empty": {
            "type": "string",
            "maxLength": 0
        },
        "intOrEmpty": {
            "oneOf": [
                {
                    "$ref": "#/definitions/empty"
                },
                {
                    "type": "integer"
                }
            ]
        },
        "stringArrayOrEmpty": {
            "oneOf": [
                {
                    "$ref": "#/definitions/empty"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "intBool": {
            "type": "integer",
            "enum": [0, 1]
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9\\-_]*$"
        },
        "equality": {
            "type": "string",
            "enum": ["==", "!="]
        },
        "field": {
            "type": "object",
            "properties": {
                "key": {
                    "$ref": "#/definitions/slug"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/slug"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "text",
                        "textarea",
                        "number",
                        "email",
                        "url",
                        "password",
                        "wysiwyg",
                        "oembed",
                        "image",
                        "file",
                        "gallery",
                        "select",
                        "checkbox",
                        "radio",
                        "true_false",
                        "post_object",
                        "page_link",
                        "relationship",
                        "taxonomy",
                        "user",
                        "google_map",
                        "date_picker",
                        "color_picker",
                        "message",
                        "tab",
                        "repeater",
                        "flexible_content"
                    ]
                },
                "instructions": {
                    "type": "string"
                },
                "required": {
                    "$ref": "#/definitions/intBool"
                },
                "conditional_logic": {
                    "oneOf": [
                        {
                            "type": "integer",
                            "enum": [0]
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "field": {
                                            "$ref": "#/definitions/slug"
                                        },
                                        "operator": {
                                            "$ref": "#/definitions/equality"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    },
                                    "required": ["field", "operator", "value"]
                                }
                            }
                        }
                    ]
                },
                "wrapper": {
                    "type": "object",
                    "properties": {
                        "width": {
                            "$ref": "#/definitions/intOrEmpty"
                        },
                        "class": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        }
                    }
                },
                "default_value": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "array",
                            "items": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "integer"
                                    }
                                ]
                            }
                        }
                    ]
                },
                "placeholder": {
                    "type": "string"
                },
                "prepend": {
                    "type": "string"
                },
                "append": {
                    "type": "string"
                },
                "maxlength": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "readonly": {
                    "$ref": "#/definitions/intBool"
                },
                "disabled": {
                    "$ref": "#/definitions/intBool"
                },

                "rows": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "new_lines": {
                    "type": "string",
                    "enum": ["", "br", "wpautop"]
                },

                "min": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "max": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "step": {
                    "$ref": "#/definitions/intOrEmpty"
                },

                "tabs": {
                    "type": "string",
                    "enum": ["all", "visual", "text"]
                },
                "toolbar": {
                    "type": "string",
                    "enum": ["full", "basic"]
                },
                "media_upload": {
                    "$ref": "#/definitions/intBool"
                },

                "width": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "height": {
                    "$ref": "#/definitions/intOrEmpty"
                },

                "return_format": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string",
                            "enum": [
                                "object",
                                "array",
                                "url",
                                "id"
                            ]
                        }
                    ]
                },
                "preview_size": {
                    "type": "string"
                },
                "library": {
                    "type": "string",
                    "enum": ["all", "uploadedTo"]
                },
                "min_width": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "min_height": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "min_size": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "max_width": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "max_height": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "max_size": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "mime_types": {
                    "type": "string"
                },

                "choices": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "allow_null": {
                    "$ref": "#/definitions/intBool"
                },
                "multiple": {
                    "$ref": "#/definitions/intBool"
                },
                "ui": {
                    "$ref": "#/definitions/intBool"
                },
                "ajax": {
                    "$ref": "#/definitions/intBool"
                },
                "other_choice": {
                    "$ref": "#/definitions/intBool"
                },
                "save_other_choice": {
                    "$ref": "#/definitions/intBool"
                },
                "layout": {
                    "type": "string",
                    "enum": [
                        "vertical",
                        "horizontal",
                        "table",
                        "block",
                        "row"
                    ]
                },
                "toggle": {
                    "$ref": "#/definitions/intBool"
                },
                "message": {
                    "type": "string"
                },

                "post_type": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "taxonomy": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "pattern": "^[a-z0-9\\-_]+:[a-z0-9\\-_]+$"
                            }
                        }
                    ]
                },
                "filters": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["search", "post_type", "taxonomy"]
                    }
                },
                "elements": {
                    "$ref": "#/definitions/stringArrayOrEmpty"
                },
                "field_type": {
                    "type": "string",
                    "enum": ["checkbox", "multi_select", "radio", "select"]
                },
                "add_term": {
                    "$ref": "#/definitions/intBool"
                },
                "save_terms": {
                    "$ref": "#/definitions/intBool"
                },
                "load_terms": {
                    "$ref": "#/definitions/intBool"
                },
                "role": {
                    "$ref": "#/definitions/stringArrayOrEmpty"
                },

                "center_lat": {
                    "oneOf": [
                        { "type": "integer" },
                        { "type": "string" }
                    ]
                },
                "center_lng": {
                    "oneOf": [
                        { "type": "integer" },
                        { "type": "string" }
                    ]
                },
                "zoom": {
                    "oneOf": [
                        { "type": "integer" },
                        { "type": "string" }
                    ]
                },

                "display_format": {
                    "type": "string"
                },
                "first_day": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 6
                },

                "esc_html": {
                    "$ref": "#/definitions/intBool"
                },

                "placement": {
                    "type": "string",
                    "enum": ["top", "left"]
                },
                "endpoint": {
                    "$ref": "#/definitions/intBool"
                },

                "collapsed": {
                    "$ref": "#/definitions/slug"
                },
                "button_label": {
                    "type": "string"
                },
                "sub_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/field"
                    }
                },
                "layouts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "$ref": "#/definitions/slug"
                            },
                            "label": {
                                "type": "string"
                            },
                            "name": {
                                "$ref": "#/definitions/slug"
                            },
                            "display": {
                                "type": "string",
                                "enum": ["table", "block", "row"]
                            },
                            "sub_fields": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/field"
                                }
                            },
                            "min": {
                                "$ref": "#/definitions/intOrEmpty"
                            },
                            "max": {
                                "$ref": "#/definitions/intOrEmpty"
                            }
                        },
                        "required": ["key", "name", "label"]
                    }
                }
            },
            "required": ["key", "label", "name", "type"]
        }
    },
    "properties": {
        "key": {
            "$ref": "#/definitions/slug"
        },
        "title": {
            "type": "string"
        },
        "fields": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/field"
            }
        },
        "location": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "param": {
                            "type": "string",
                            "enum": [
                                "post_type",
                                "post_status",
                                "post_format",
                                "post_category",
                                "post_taxonomy",
                                "post",
                                "page_template",
                                "page_type",
                                "page_parent",
                                "page",
                                "current_user",
                                "current_user_role",
                                "user_form",
                                "user_role",
                                "attachment",
                                "taxonomy",
                                "comment",
                                "widget",
                                "options_page"
                            ]
                        },
                        "operator": {
                            "$ref": "#/definitions/equality"
                        },
                        "value": {
                            "oneOf": [
                                { "type": "string" },
                                { "type": "integer" }
                            ]
                        }
                    },
                    "required": ["param", "operator", "value"]
                }
            }
        },
        "menu_order": {
            "type": "integer"
        },
        "position": {
            "type": "string",
            "enum": ["normal", "high", "side"]
        },
        "style": {
            "type": "string",
            "enum": ["default", "seamless"]
        },
        "label_placement": {
            "type": "string",
            "enum": ["top", "left"]
        },
        "instruction_placement": {
            "type": "string",
            "enum": ["label", "field"]
        },
        "hide_on_screen": {
            "oneOf": [
                {
                    "$ref": "#/definitions/empty"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "active": {
            "$ref": "#/definitions/intBool"
        },
        "description": {
            "type": "string"
        },
        "private": {
            "$ref": "#/definitions/intBool"
        },
        "modified": {
            "type": "integer"
        }
    },
    "required": [ "key", "title", "fields" ]
}

=== asmbs/wp-schedule-builder/resources/acf/session/location.json
{
    "key": "session--location",
    "title": "Location",
    "description": "Set the location of a session.",
    "fields": [
        {
            "key": "location--venue",
            "name": "venue",
            "label": "Venue",
            "type": "select",
            "multiple": 0,
            "choices": {
                "tba": "TBA"
            },
            "ui": 1,
            "default_value": "tba"
        },
        {
            "key": "location--room",
            "name": "room",
            "label": "Room",
            "type": "select",
            "multiple": 0,
            "choices": {
                "_": "(None)",
                "tba": "TBA"
            },
            "ui": 1,
            "default_value": "_",
            "allow_null": 0
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "session"
            }
        ]
    ],
    "menu_order": 20,
    "position": "side",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": "",
    "active": 1,
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/abstract/basic.json
{
    "key": "abstract--basic",
    "title": "Basic Information",
    "fields": [
        {
            "key": "basic--id",
            "name": "abstract_id",
            "label": "ID",
            "type": "text",
            "wrapper": {
                "width": 15
            },
            "required": 1
        },
        {
            "key": "basic--title",
            "name": "title",
            "label": "Title",
            "type": "text",
            "wrapper": {
                "width": 85
            },
            "required": 1
        },
        {
            "key": "basic--authors",
            "name": "authors",
            "label": "Authors",
            "type": "post_object",
            "post_type": ["author"],
            "multiple": 1
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "abstract"
            }
        ]
    ],
    "menu_order": 0,
    "position": "normal",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/faculty/profile.json
{
    "key": "faculty--profile",
    "title": "Profile",
    "fields": [
        {
            "key": "profile--photo",
            "name": "photo",
            "label": "Photo",
            "type": "image",
            "preview_size": "medium",
            "wrapper": {
                "width": 30
            }
        },
        {
            "key": "profile--bio",
            "name": "bio",
            "label": "Biography",
            "type": "textarea",
            "rows": 12,
            "wrapper": {
                "width": 70
            }
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "speaker"
            }
        ],
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "author"
            }
        ],
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "person"
            }
        ]
    ],
    "menu_order": 10,
    "position": "normal",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/_options/logistics.json
{
    "key": "options--logistics",
    "title": "Event Logistics",
    "description": "",
    "fields": [
        {
            "key": "logistics--dates",
            "name": "dates",
            "label": "Event Dates",
            "instructions": "Enter each date of the meeting that can be programmed with sessions. They'll be shown in the session editor <em>in the order shown here.</em>",
            "type": "repeater",
            "button_label": "+ Date",
            "sub_fields": [
                {
                    "key": "logistics--dates--value",
                    "name": "value",
                    "label": "Value",
                    "instructions": "<code>YYYY/MM/DD</code> format",
                    "type": "text",
                    "placeholder": "ex. 3\/31\/2016",
                    "wrapper": {
                        "width": 20
                    }
                },
                {
                    "key": "logistics--dates--label",
                    "name": "label",
                    "label": "Label",
                    "type": "text",
                    "placeholder": "ex. Thursday (3\/31)"
                }
            ],
            "min": 1
        },
        {
            "key": "logistics--locations",
            "name": "locations",
            "label": "Location Venues",
            "instructions": "",
            "type": "repeater",
            "layout": "block",
            "button_label": "+ Venue",
            "sub_fields": [
                {
                    "key": "logistics--locations--name",
                    "name": "location_name",
                    "label": "Name",
                    "type": "text"
                },
                {
                    "key": "logistics--locations--shortname",
                    "name": "location_shortname",
                    "label": "Short Name",
                    "type": "text"
                },
                {
                    "key": "logistics--locations--rooms",
                    "name": "location_rooms",
                    "label": "Rooms",
                    "type": "repeater",
                    "layout": "table",
                    "button_label": "+ Room",
                    "sub_fields": [
                        {
                            "key": "logistics--locations--rooms--name",
                            "name": "room_name",
                            "label": "Room",
                            "type": "text"
                        }
                    ]
                }
            ]
        }
    ],
    "location": [
        [
            {
                "param": "options_page",
                "operator": "==",
                "value": "sb_options"
            }
        ]
    ],
    "menu_order": 0,
    "position": "normal",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": "",
    "active": 1,
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/session/faculty.json
{
    "key": "session--faculty",
    "title": "Session Faculty",
    "fields": [
        {
            "key": "faculty--groups",
            "name": "faculty_groups",
            "label": "Faculty Groups",
            "instructions": "Add faculty listings like course directors, session chairs, moderators, etc.",
            "type": "repeater",
            "layout": "table",
            "button_label": "+ Add Group",
            "sub_fields": [
                {
                    "key": "faculty--groups--label",
                    "name": "label",
                    "label": "Label",
                    "type": "text",
                    "wrapper": {
                        "width": 25
                    }
                },
                {
                    "key": "faculty--groups--people",
                    "name": "people",
                    "label": "People",
                    "type": "post_object",
                    "post_type": ["person"],
                    "multiple": 1,
                    "wrapper": {
                        "width": 75
                    }
                }
            ]
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "session"
            }
        ]
    ],
    "menu_order": 25,
    "position": "normal",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/_options/event_details.json
{
    "key": "options--event_details",
    "title": "Event Details",
    "description": "",
    "fields": [
        {
            "key": "event_details--dates",
            "name": "dates",
            "label": "Event Dates",
            "instructions": "Enter each date of the meeting that can be programmed with sessions. They'll be shown in the session editor <em>in the order shown here.</em>",
            "type": "repeater",
            "button_label": "+ Date",
            "sub_fields": [
                {
                    "key": "event_details--dates--value",
                    "name": "value",
                    "label": "Value",
                    "type": "text",
                    "placeholder": "ex. 3\/31\/2016",
                    "wrapper": {
                        "width": 20
                    }
                },
                {
                    "key": "event_details--dates--label",
                    "name": "label",
                    "label": "Label",
                    "type": "text",
                    "placeholder": "ex. Thursday (3\/31)"
                }
            ],
            "min": 1
        },
        {
            "key": "event_details--locations",
            "name": "locations",
            "label": "Location Venues",
            "instructions": "",
            "type": "repeater",
            "layout": "block",
            "button_label": "+ Venue",
            "sub_fields": [
                {
                    "key": "event_details--locations--name",
                    "name": "location_name",
                    "label": "Name",
                    "type": "text"
                }
            ]
        }
    ],
    "location": [
        [
            {
                "param": "options_page",
                "operator": "==",
                "value": "sb_options"
            }
        ]
    ],
    "menu_order": 0,
    "position": "normal",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": "",
    "active": 1,
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/session/evaluable.json
{
    "key": "session--evaluation",
    "title": "Session Evaluation",
    "fields": [
        {
            "key": "session--evaluable",
            "name": "evaluable",
            "label": "Evaluable",
            "instructions": "Does this session have a dedicated evaluation?",
            "type": "true_false",
            "required": 0,
            "conditional_logic": 0,
            "wrapper": {
                "width": "",
                "class": "",
                "id": ""
            },
            "message": "",
            "default_value": 0,
            "ui": 1,
            "ui_on_text": "",
            "ui_off_text": ""
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "session"
            }
        ]
    ],
    "menu_order": 30,
    "position": "side",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": "",
    "active": 1,
    "description": "",
    "private": 1
}
