=== asmbs/wp-schedule-builder/resources/schema/field_group.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://advancedcustomfields.com/json-schema/field_group",
    "type": "object",
    "definitions": {
        "empty": {
            "type": "string",
            "maxLength": 0
        },
        "intOrEmpty": {
            "oneOf": [
                {
                    "$ref": "#/definitions/empty"
                },
                {
                    "type": "integer"
                }
            ]
        },
        "stringArrayOrEmpty": {
            "oneOf": [
                {
                    "$ref": "#/definitions/empty"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "intBool": {
            "type": "integer",
            "enum": [0, 1]
        },
        "slug": {
            "type": "string",
            "pattern": "^[a-z0-9\\-_]*$"
        },
        "equality": {
            "type": "string",
            "enum": ["==", "!="]
        },
        "field": {
            "type": "object",
            "properties": {
                "key": {
                    "$ref": "#/definitions/slug"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/slug"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "text",
                        "textarea",
                        "number",
                        "email",
                        "url",
                        "password",
                        "wysiwyg",
                        "oembed",
                        "image",
                        "file",
                        "gallery",
                        "select",
                        "checkbox",
                        "radio",
                        "true_false",
                        "post_object",
                        "page_link",
                        "relationship",
                        "taxonomy",
                        "user",
                        "google_map",
                        "date_picker",
                        "color_picker",
                        "message",
                        "tab",
                        "repeater",
                        "flexible_content"
                    ]
                },
                "instructions": {
                    "type": "string"
                },
                "required": {
                    "$ref": "#/definitions/intBool"
                },
                "conditional_logic": {
                    "oneOf": [
                        {
                            "type": "integer",
                            "enum": [0]
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "field": {
                                            "$ref": "#/definitions/slug"
                                        },
                                        "operator": {
                                            "$ref": "#/definitions/equality"
                                        },
                                        "value": {
                                            "type": "string"
                                        }
                                    },
                                    "required": ["field", "operator", "value"]
                                }
                            }
                        }
                    ]
                },
                "wrapper": {
                    "type": "object",
                    "properties": {
                        "width": {
                            "$ref": "#/definitions/intOrEmpty"
                        },
                        "class": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        }
                    }
                },
                "default_value": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "array",
                            "items": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "integer"
                                    }
                                ]
                            }
                        }
                    ]
                },
                "placeholder": {
                    "type": "string"
                },
                "prepend": {
                    "type": "string"
                },
                "append": {
                    "type": "string"
                },
                "maxlength": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "readonly": {
                    "$ref": "#/definitions/intBool"
                },
                "disabled": {
                    "$ref": "#/definitions/intBool"
                },

                "rows": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "new_lines": {
                    "type": "string",
                    "enum": ["", "br", "wpautop"]
                },

                "min": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "max": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "step": {
                    "$ref": "#/definitions/intOrEmpty"
                },

                "tabs": {
                    "type": "string",
                    "enum": ["all", "visual", "text"]
                },
                "toolbar": {
                    "type": "string",
                    "enum": ["full", "basic"]
                },
                "media_upload": {
                    "$ref": "#/definitions/intBool"
                },

                "width": {
                    "$ref": "#/definitions/intOrEmpty"
                },
                "height": {
                    "$ref": "#/definitions/intOrEmpty"
                },

                "return_format": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string",
                            "enum": [
                                "object",
                                "array",
                                "url",
                                "id"
                            ]
                        }
                    ]
                },
                "preview_size": {
                    "type": "string"
                },
                "library": {
                    "type": "string",
                    "enum": ["all", "uploadedTo"]
                },
                "min_width": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "min_height": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "min_size": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "max_width": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "max_height": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "max_size": {
                    "oneOf": [
                        { "type": "string" },
                        { "type": "integer" }
                    ]
                },
                "mime_types": {
                    "type": "string"
                },

                "choices": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "allow_null": {
                    "$ref": "#/definitions/intBool"
                },
                "multiple": {
                    "$ref": "#/definitions/intBool"
                },
                "ui": {
                    "$ref": "#/definitions/intBool"
                },
                "ajax": {
                    "$ref": "#/definitions/intBool"
                },
                "other_choice": {
                    "$ref": "#/definitions/intBool"
                },
                "save_other_choice": {
                    "$ref": "#/definitions/intBool"
                },
                "layout": {
                    "type": "string",
                    "enum": [
                        "vertical",
                        "horizontal",
                        "table",
                        "block",
                        "row"
                    ]
                },
                "toggle": {
                    "$ref": "#/definitions/intBool"
                },
                "message": {
                    "type": "string"
                },

                "post_type": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "taxonomy": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "pattern": "^[a-z0-9\\-_]+:[a-z0-9\\-_]+$"
                            }
                        }
                    ]
                },
                "filters": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": ["search", "post_type", "taxonomy"]
                    }
                },
                "elements": {
                    "$ref": "#/definitions/stringArrayOrEmpty"
                },
                "field_type": {
                    "type": "string",
                    "enum": ["checkbox", "multi_select", "radio", "select"]
                },
                "add_term": {
                    "$ref": "#/definitions/intBool"
                },
                "save_terms": {
                    "$ref": "#/definitions/intBool"
                },
                "load_terms": {
                    "$ref": "#/definitions/intBool"
                },
                "role": {
                    "$ref": "#/definitions/stringArrayOrEmpty"
                },

                "center_lat": {
                    "oneOf": [
                        { "type": "integer" },
                        { "type": "string" }
                    ]
                },
                "center_lng": {
                    "oneOf": [
                        { "type": "integer" },
                        { "type": "string" }
                    ]
                },
                "zoom": {
                    "oneOf": [
                        { "type": "integer" },
                        { "type": "string" }
                    ]
                },

                "display_format": {
                    "type": "string"
                },
                "first_day": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 6
                },

                "esc_html": {
                    "$ref": "#/definitions/intBool"
                },

                "placement": {
                    "type": "string",
                    "enum": ["top", "left"]
                },
                "endpoint": {
                    "$ref": "#/definitions/intBool"
                },

                "collapsed": {
                    "$ref": "#/definitions/slug"
                },
                "button_label": {
                    "type": "string"
                },
                "sub_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/field"
                    }
                },
                "layouts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "$ref": "#/definitions/slug"
                            },
                            "label": {
                                "type": "string"
                            },
                            "name": {
                                "$ref": "#/definitions/slug"
                            },
                            "display": {
                                "type": "string",
                                "enum": ["table", "block", "row"]
                            },
                            "sub_fields": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/field"
                                }
                            },
                            "min": {
                                "$ref": "#/definitions/intOrEmpty"
                            },
                            "max": {
                                "$ref": "#/definitions/intOrEmpty"
                            }
                        },
                        "required": ["key", "name", "label"]
                    }
                }
            },
            "required": ["key", "label", "name", "type"]
        }
    },
    "properties": {
        "key": {
            "$ref": "#/definitions/slug"
        },
        "title": {
            "type": "string"
        },
        "fields": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/field"
            }
        },
        "location": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "param": {
                            "type": "string",
                            "enum": [
                                "post_type",
                                "post_status",
                                "post_format",
                                "post_category",
                                "post_taxonomy",
                                "post",
                                "page_template",
                                "page_type",
                                "page_parent",
                                "page",
                                "current_user",
                                "current_user_role",
                                "user_form",
                                "user_role",
                                "attachment",
                                "taxonomy",
                                "comment",
                                "widget",
                                "options_page"
                            ]
                        },
                        "operator": {
                            "$ref": "#/definitions/equality"
                        },
                        "value": {
                            "oneOf": [
                                { "type": "string" },
                                { "type": "integer" }
                            ]
                        }
                    },
                    "required": ["param", "operator", "value"]
                }
            }
        },
        "menu_order": {
            "type": "integer"
        },
        "position": {
            "type": "string",
            "enum": ["normal", "high", "side"]
        },
        "style": {
            "type": "string",
            "enum": ["default", "seamless"]
        },
        "label_placement": {
            "type": "string",
            "enum": ["top", "left"]
        },
        "instruction_placement": {
            "type": "string",
            "enum": ["label", "field"]
        },
        "hide_on_screen": {
            "oneOf": [
                {
                    "$ref": "#/definitions/empty"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "active": {
            "$ref": "#/definitions/intBool"
        },
        "description": {
            "type": "string"
        },
        "private": {
            "$ref": "#/definitions/intBool"
        },
        "modified": {
            "type": "integer"
        }
    },
    "required": [ "key", "title", "fields" ]
}

=== asmbs/wp-schedule-builder/resources/acf/session/test.json
{
    "key": "session__test",
    "title": "Test Group",
    "fields": [
        {
            "key": "test__field1",
            "label": "Field One",
            "name": "field1",
            "type": "text"
        },
        {
            "key": "test__field2",
            "label": "Field Two",
            "name": "field2",
            "type": "radio",
            "choices": {
                "x": "X",
                "y": "Y"
            }
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "session"
            }
        ]
    ],
    "active": 1
}

=== asmbs/wp-schedule-builder/resources/acf/session/scheduling.json
{
    "key": "session--scheduling",
    "title": "Scheduling",
    "description": "Define the date and time a session takes place.",
    "fields": [
        {
            "key": "scheduling--date",
            "name": "date",
            "label": "Meeting Date",
            "type": "radio",
            "choices": {
                "tba": "TBA"
            },
            "default_value": "tba"
        },
        {
            "key": "scheduling--start",
            "name": "start_time",
            "label": "Start Time",
            "type": "text"
        },
        {
            "key": "scheduling--end",
            "name": "end_time",
            "label": "End Time",
            "type": "text"
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "session"
            }
        ]
    ],
    "menu_order": 10,
    "position": "side",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": "",
    "active": 1,
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/faculty/_staff_user_person.json
{
    "key": "person--staff_use",
    "title": "Staff Use",
    "fields": [
        {
            "key": "person--staff_use--id",
            "name": "person_id",
            "label": "Person ID",
            "type": "text",
            "wrapper": {
                "width": 20
            }
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "person"
            }
        ]
    ],
    "menu_order": 0,
    "position": "normal",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/_options/timezone.json
{
    "key": "options-timezone",
    "title": "Timezone",
    "fields": [
        {
            "key": "timezone--select",
            "label": "Timezone",
            "name": "timezone",
            "type": "select",
            "instructions": "Select the venue timezone to be used on schedule and session pages.",
            "required": 0,
            "conditional_logic": 0,
            "wrapper": {
                "width": "",
                "class": "",
                "id": ""
            },
            "choices": {
                "EDT": "EDT (Eastern Daylight Time  | UTC−04)",
                "EST": "EST (Eastern Standard Time  | UTC−05)",
                "ET": "ET (Eastern Time  | UTC−05 \/ UTC−04)",
                "CDT": "CDT (Central Daylight Time  | UTC−05)",
                "CST": "CST (Central Standard Time  | UTC−06)",
                "CT": "CT (Central Time | UTC−06\/UTC−05)",
                "MDT": "MDT (Mountain Daylight Time  | UTC−06)",
                "MST": "MST (Mountain Standard Time  | UTC−07)",
                "PDT": "PDT (Pacific Daylight Time  | UTC−07)",
                "PST": "PST (Pacific Standard Time  | UTC−08)",
                "AKDT": "AKDT (Alaska Daylight Time | UTC−08)",
                "AKST": "AKST (Alaska Standard Time | UTC−09)",
                "HDT": "HDT (Hawaii–Aleutian Daylight Time | UTC−09)",
                "HST": "HST (Hawaii–Aleutian Standard Time | UTC−10)"
            },
            "default_value": "ET",
            "allow_null": 0,
            "multiple": 0,
            "ui": 0,
            "return_format": "value",
            "ajax": 0,
            "placeholder": ""
        }
    ],
    "location": [
        [
            {
                "param": "options_page",
                "operator": "==",
                "value": "sb_options"
            }
        ]
    ],
    "menu_order": 0,
    "position": "side",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": "",
    "active": 1,
    "private": 1,
    "description": ""
}

=== asmbs/wp-schedule-builder/resources/acf/session/_staff_use.json
{
    "key": "session--staff_use",
    "title": "Staff Use",
    "fields": [
        {
            "key": "staff_use--progress",
            "name": "progress",
            "label": "Progress",
            "type": "checkbox",
            "choices": {
                "datetime": "Date & Time",
                "location": "Location",
                "objectives": "Objectives",
                "outline": "Outline/Agenda",
                "speakers": "Speakers"
            },
            "layout": "horizontal"
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "session"
            }
        ]
    ],
    "menu_order": 0,
    "position": "normal",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/_options/accreditation.json
{
    "key": "options--accreditation",
    "title": "Accreditation",
    "fields": [
        {
            "key": "accreditation--types",
            "name": "credit_types",
            "label": "Credit Types",
            "type": "repeater",
            "button_label": "+ Add Type",
            "sub_fields": [
                {
                    "key": "accreditation--types--type",
                    "name": "type",
                    "label": "Type",
                    "type": "text",
                    "placeholder": "ex. CME"
                }
            ]
        },
        {
            "key": "accreditation--statement",
            "name": "accreditation_statement",
            "label": "Statement",
            "instructions": "Enter the official meeting accreditation statement here. Markdown is supported, but won't be syntax-highlighted like it is in the post editor.",
            "type": "textarea",
            "rows": 16
        }
    ],
    "location": [
        [
            {
                "param": "options_page",
                "operator": "==",
                "value": "sb_options"
            }
        ]
    ],
    "menu_order": 0,
    "position": "side",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/abstract/classification.json
{
    "key": "abstract--taxonomy",
    "title": "Classification",
    "fields": [
        {
            "key": "taxonomy--type",
            "name": "abstract_type",
            "label": "Abstract Type",
            "type": "taxonomy",
            "taxonomy": "abstract-type",
            "field_type": "select",
            "save_terms": 1,
            "add_term": 0
        },
        {
            "key": "taxonomy--society",
            "name": "society",
            "label": "Societies",
            "type": "taxonomy",
            "taxonomy": "society",
            "field_type": "checkbox",
            "save_terms": 1,
            "add_term": 0
        },
        {
            "key": "taxonomy--keyword",
            "name": "keyword",
            "label": "Keywords",
            "type": "taxonomy",
            "taxonomy": "keyword",
            "field_type": "multi_select",
            "save_terms": 1,
            "add_term": 0
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "abstract"
            }
        ]
    ],
    "menu_order": 5,
    "position": "side",
    "private": 1
}

=== asmbs/wp-schedule-builder/resources/acf/faculty/_staff_use_speaker.json
{
    "key": "speaker--staff_use",
    "title": "Staff Use",
    "fields": [
        {
            "key": "speaker--staff_use--id",
            "name": "speaker_id",
            "label": "Speaker ID",
            "type": "text",
            "wrapper": {
                "width": 20
            }
        }
    ],
    "location": [
        [
            {
                "param": "post_type",
                "operator": "==",
                "value": "speaker"
            }
        ]
    ],
    "menu_order": 0,
    "position": "normal",
    "private": 1
}
